### ISSUE TITLE
Getting forwarded to IPB login page

### ISSUE THREAD

**Issue by RichusX** [Lavoaster/IPS-SteamLoginMethod#75]
When I click sign in with steam this is what happens: http://i.cubeupload.com/v64eTm.gif

I assume this is not the correct behaviour, correct?

**Comment by madman32395** [comment]
Please contact me on steam, If you want I can jump on and take a poke at it. See whats happening. http://steamcommunity.com/id/madman32395

**Comment by madman32395** [comment]
but any red text talking about could not be completed at this time or anything? 
using lastest from IPS or Github? (in relation to the plugin)
Uploaded the upload folder correctly?

**Comment by RichusX** [comment]
No red text or any error message at all. Using latest from GitHub.
Uploaded correctly AFAIK.

Will add you on Steam once I get home.

**Comment by mauvalente** [comment]
Hello!
I'm getting the same problem. No errors in php log.
The problem happens when I enable the ssl login.

Is that a clue?

**Comment by madman32395** [comment]
@mauvalente enabling SSL shouldnt have affect on this unless the webserver is improperly setup for redirecting; mod_sec; and ive also seen cloudflare mess stuff up when improperly setup.

**Comment by ADKGamers** [comment]
What type of hosting are you on?  I'm currently testing something that might have fixed this, but am running into another issue so won't have a for sure answer if my solution worked for me.

**Comment by madman32395** [comment]
Change your global_conf to https

**Comment by mauvalente** [comment]
Hello ADKGamers, I'm using NGinx as webservice.  Is there any special config for this ws?

**Comment by RichusX** [comment]
@ADKGamers I'm running nginx on a VPS (self-hosted).

**Comment by ADKGamers** [comment]
@RichusX and @mauvalente  - I had a similar issue where it was just redirecting back to the screen like the short clip in the original post.  

What fixed that issue was actually making sure that the server time was sync'd properly.  The only reason I found out that was the problem was because I have was having an issue with 2FA, which was caused due to the server time not being sync'd properly. 

So I'm not saying that this is the reason for your issues, but that might be something to check out to see if that fixes it for you.

**Comment by RichusX** [comment]
My server syncs time with NTP pool (uk.pool.ntp.org) so there should be no issue there.
